services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    ports:
      - "5000:5000"
    depends_on:
      - db
    entrypoint: ["/app/entrypoint.sh"]

  db:
    image: postgres:15
    env_file:
      - .env.prod
    volumes:
      - db_prod_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_prod_data:
