[project]
name = "sgr-coin-calculator-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "flask-migrate>=4.1.0",
    "load-dotenv>=0.1.0",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.43",
]
