"""Initial migration

Revision ID: 0361099e2e24
Revises: 
Create Date: 2025-09-11 12:17:26.395317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0361099e2e24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('share', sa.Float(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('position')
    )
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('rank_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_table('ranks')
    # ### end Alembic commands ###
