"""Test

Revision ID: 147176c0b1fd
Revises: dfbd6fa6e884
Create Date: 2025-08-29 11:27:21.957299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147176c0b1fd'
down_revision = 'dfbd6fa6e884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.alter_column('share',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.alter_column('share',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
