"""Add member job association object

Revision ID: 42421ae01481
Revises: 6e9ce9ed0060
Create Date: 2025-09-11 15:37:07.893243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42421ae01481'
down_revision = '6e9ce9ed0060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('member_job',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('member_rank', sa.String(), nullable=False),
    sa.Column('member_pay', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'job_id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint(batch_op.f('members_rank_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ranks', ['rank_id'], ['id'])

    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.alter_column('share',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('share',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('members_rank_id_fkey'), 'ranks', ['rank_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('member_job')
    op.drop_table('job')
    # ### end Alembic commands ###
