"""test-update

Revision ID: 60d7659cc178
Revises: dd817b2f68c3
Create Date: 2025-09-03 14:11:12.604456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d7659cc178'
down_revision = 'dd817b2f68c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testField', sa.String(length=20), nullable=True))
        batch_op.alter_column('share',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.alter_column('share',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('testField')

    # ### end Alembic commands ###
