"""adjust-relationships

Revision ID: 7a11bff0327c
Revises: 6ec63e5ef8f6
Create Date: 2025-09-08 10:04:22.791414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a11bff0327c'
down_revision = '6ec63e5ef8f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.alter_column('share',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.alter_column('share',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
