"""Review title field

Revision ID: bcfa947b995e
Revises: 312c19dc9eae
Create Date: 2025-09-12 10:24:43.395591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfa947b995e'
down_revision = '312c19dc9eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.alter_column('share',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.alter_column('share',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
