"""Add job model

Revision ID: bf0c7f86510b
Revises: 42421ae01481
Create Date: 2025-09-12 09:48:56.127454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0c7f86510b'
down_revision = '42421ae01481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('job_description', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_silver', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('company_cut_amt', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('remainder_after_payouts', sa.Float(), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('title')

    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.alter_column('share',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.alter_column('share',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('remainder_after_payouts')
        batch_op.drop_column('company_cut_amt')
        batch_op.drop_column('total_silver')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('job_description')
        batch_op.drop_column('job_name')

    # ### end Alembic commands ###
